/** Transforms compared between the local evaluator and the tenant preview. Bob.Kelso has no middleName. */
const missing = { type: 'identityAttribute', attributes: { name: 'middleName' } };
const tpl = (value, extra = {}) => ({ type: 'static', attributes: { value, ...extra } });

export const CASES = [
  ['concat with null', { type: 'concat', attributes: { values: ['a', missing, 'b'] } }],
  ['join with null', { type: 'join', attributes: { values: ['a', missing, 'b'], separator: '-' } }],
  ['velocity empty string in #if', tpl('#set($e = "")#if($e)T#{else}F#end')],
  ['velocity multi-line', tpl('#if(true)\nA\n#end\nB\n#set($x = 1)\nC')],
  ['velocity "1" == 1', tpl('#if("1" == 1)T#{else}F#end')],
  ['velocity arithmetic', tpl('#set($n = 2 + 3)$n')],
  ['velocity interpolation', tpl('#set($n = "Ada")#set($m = "Hi $n")$m')],
  ['velocity undefined ref', tpl('x$nope y')],
  ['velocity null result', tpl('#set($x = null)$x')],
  ['velocity foreach', tpl('#foreach($i in [1..3])$i#end')],
  ['velocity string methods', tpl('$a.substring(0, 3).toUpperCase()|$a.replaceAll("[aeiou]", "_")|$a.split(",").size()', { a: 'banana,x' })],
  ['substring out of range', { type: 'substring', attributes: { input: 'abc', begin: 1, end: 10 } }],
  ['substring offsets', { type: 'substring', attributes: { input: 'abcdef', begin: 1, beginOffset: 1, end: 4 } }],
  ['split trailing empty', { type: 'split', attributes: { input: 'a,b,,', delimiter: ',', index: 3 } }],
  ['replace regex', { type: 'replace', attributes: { input: 'a.b.c', regex: '\\.', replacement: '-' } }],
  ['replace groups', { type: 'replace', attributes: { input: 'John Smith', regex: '(\\w+) (\\w+)', replacement: '$2 $1' } }],
  ['replaceAll table', { type: 'replaceAll', attributes: { input: 'a-b_c', table: { '-': ' ', _: '.' } } }],
  ['dateFormat zone', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00Z', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd HH:mm z' } }],
  ['dateFormat epoch', { type: 'dateFormat', attributes: { input: '1700000000000', inputFormat: 'EPOCH_TIME_JAVA', outputFormat: 'ISO8601' } }],
  ['dateFormat pattern in', { type: 'dateFormat', attributes: { input: '03/29/2026', inputFormat: 'MM/dd/yyyy', outputFormat: 'ISO8601' } }],
  ['dateMath month end', { type: 'dateMath', attributes: { input: '2026-01-31T00:00:00Z', expression: '+1M' } }],
  ['dateMath round', { type: 'dateMath', attributes: { input: '2026-01-31T15:20:00Z', expression: '+1d/d', roundUp: true } }],
  ['dateCompare now', { type: 'dateCompare', attributes: { firstDate: '2026-01-01T00:00:00Z', secondDate: 'now', operator: 'LT', positiveCondition: 'yes', negativeCondition: 'no' } }],
  ['conditional', { type: 'conditional', attributes: { expression: '$a eq ABC', a: 'ABC', positiveCondition: 'yes', negativeCondition: 'no' } }],
  ['e164phone FR', { type: 'e164phone', attributes: { input: '06 12 34 56 78', defaultRegion: 'FR' } }],
  ['iso3166', { type: 'iso3166', attributes: { input: 'France' } }],
  ['normalizeNames', { type: 'normalizeNames', attributes: { input: "JEAN-PIERRE o'neil mcdonald III" } }],
  ['decomposeDiacriticalMarks', { type: 'decomposeDiacriticalMarks', attributes: { input: 'Élodie Ñúñez' } }],
  ['leftPad', { type: 'leftPad', attributes: { input: '7', length: 3, padding: '0' } }],
  ['lookup no match', { type: 'lookup', attributes: { input: 'XX', table: { US: 'United States' } } }],
  ['firstValid all null', { type: 'firstValid', attributes: { values: [missing, missing] } }],
  ['base64Encode accent', { type: 'base64Encode', attributes: { input: 'é' } }],
  ['lower of null', { type: 'lower', attributes: { input: missing } }],
  ['replace forceNull, matching', { type: 'replace', attributes: { input: 'NULL_VALUE', regex: 'NULL_VALUE', replacement: '#set($forceNull = null)$forceNull' } }],
  ['replace forceNull, not matching', { type: 'replace', attributes: { input: 'O365-S', regex: 'NULL_VALUE', replacement: '#set($forceNull = null)$forceNull' } }],
  ['velocity quiet null', tpl('a$!x b', { x: missing })],
  ['velocity null variable', tpl('a$x b', { x: missing })],
  ['dateFormat zone letter X', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00Z', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd HH:mm X' } }],
  ['dateFormat plain pattern out', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00Z', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd HH:mm' } }],
  ['dateMath round down', { type: 'dateMath', attributes: { input: '2026-01-31T15:20:00Z', expression: '/d' } }],
  ['dateMath round up on boundary', { type: 'dateMath', attributes: { input: '2026-01-31T00:00:00Z', expression: '/d', roundUp: true } }],
  ['split regex delimiter', { type: 'split', attributes: { input: 'a1b22c', delimiter: '\\d+', index: 2 } }],
  ['dateFormat ISO millis in', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00.000Z', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd HH:mm' } }],
  ['dateFormat ISO date only in', { type: 'dateFormat', attributes: { input: '2026-03-29', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd' } }],
  ['dateFormat ISO offset in', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00+02:00', inputFormat: 'ISO8601', outputFormat: 'yyyy-MM-dd HH:mm' } }],
  ['dateFormat no formats', { type: 'dateFormat', attributes: { input: '2026-03-29T01:30:00Z' } }],
  ['dateFormat bad input', { type: 'dateFormat', attributes: { input: 'notadate', inputFormat: 'MM/dd/yyyy', outputFormat: 'ISO8601' } }],
  ['dateFormat pattern to pattern', { type: 'dateFormat', attributes: { input: '03/29/2026', inputFormat: 'MM/dd/yyyy', outputFormat: 'dd.MM.yyyy' } }],
  ['dateFormat pattern to zone z', { type: 'dateFormat', attributes: { input: '03/29/2026', inputFormat: 'MM/dd/yyyy', outputFormat: 'yyyy-MM-dd HH:mm z' } }],
  ['velocity quiet undefined', tpl('a$!nope b')],
  ['velocity quiet after set null', tpl('#set($x = null)a$!x b')],
  ['velocity quiet empty string', tpl('a$!x b', { x: '' })],
];
